version: "3.3"
services:
  selenium:
    image: registry.ahamon.ovh/ca22_selenium
    command: -m scraper.main
    environment:
      - PUSHED_APP_KEY 
      - PUSHED_APP_SECRET 
      - CA_LOGIN 
      - CA_PASSWORD 
      - CA_ACCOUNT 
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 6,18 * * *"
        - "swarm.cronjob.skip-running=false"
      restart_policy:
        condition: none
      resources:
        reservations:
          memory: 900m
